In [1]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/AQI_Project/data/city_day.csv')
df.head()

Mounted at /content/drive

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN

In [2]:
df = df.dropna(subset=['AQI'])
print(df.shape)

(24850, 16)

In [3]:
city_avg = df.groupby('City')['AQI'].mean().sort_values(ascending=False)
print(city_avg.head(5)) # most polluted
print(city_avg.tail(5)) # least polluted

City
Ahmedabad    452.122939
Delhi        259.487744
Patna        240.782042
Gurugram     225.123882
Lucknow      217.973059
Name: AQI, dtype: float64
City
Ernakulam             92.359477
Thiruvananthapuram    75.878327
Coimbatore            73.023256
Shillong              53.795122
Aizawl                34.765766
Name: AQI, dtype: float64

In [4]:
df[['PM2.5', 'PM10', 'NO2', 'CO', 'AQI']].corr()

          PM2.5      PM10       NO2        CO       AQI
PM2.5  1.000000  0.853200  0.366404  0.093524  0.659181
PM10   0.853200  1.000000  0.483121  0.116719  0.803313
NO2    0.366404  0.483121  1.000000  0.371186  0.537071
CO     0.093524  0.116719  0.371186  1.000000  0.683346
AQI    0.659181  0.803313  0.537071  0.683346  1.000000

The pollutant most strongly linked to AQI is PM10, with a correlation coefficient of 0.803313.

The relationship is positive, meaning that as PM10 increases, AQI tends to increase.

 Pearson correlation

In [7]:
from scipy.stats import pearsonr
data = df[['PM2.5', 'AQI']].dropna()
r, p = pearsonr(data['PM2.5'], data['AQI'])
print(r)

0.6591810111093792

In [8]:
x = data['PM2.5']
y = data['AQI']
n = len(x)
r_manual = (n*(x*y).sum() - x.sum()*y.sum()) / (
((n*(x**2).sum() - x.sum()**2) * (n*(y**2).sum() - y.sum()**2)) ** 0.5)
print(r_manual)

0.6591810111093785

AQI_Category

In [10]:
def get_aqi_category(aqi):
    if aqi <= 50:
        return 'Good'
    elif aqi <= 100:
        return 'Satisfactory'
    elif aqi <= 200:
        return 'Moderate'
    elif aqi <= 300:
        return 'Poor'
    elif aqi <= 400:
        return 'Very Poor'
    else:
        return 'Severe'

In [11]:
df['AQI_Category'] = df['AQI'].apply(get_aqi_category)

In [12]:
df[['AQI', 'AQI_Category']].head()

      AQI AQI_Category
28  209.0         Poor
29  328.0    Very Poor
30  514.0       Severe
31  782.0       Severe
32  914.0       Severe

In [13]:
print(df['AQI_Category'].value_counts())
print(df.nlargest(5, 'AQI')[['City', 'Date', 'AQI']])
print(df.sort_values('AQI', ascending=False).head(10))

AQI_Category
Moderate        8829
Satisfactory    8224
Poor            2781
Very Poor       2337
Good            1341
Severe          1338
Name: count, dtype: int64
           City        Date     AQI
1145  Ahmedabad  2018-02-19  2049.0
1136  Ahmedabad  2018-02-10  1917.0
560   Ahmedabad  2016-07-14  1842.0
1048  Ahmedabad  2017-11-14  1747.0
1463  Ahmedabad  2019-01-03  1719.0
           City        Date   PM2.5    PM10      NO     NO2     NOx  NH3  \
1145  Ahmedabad  2018-02-19  242.66     NaN  132.47  199.17  246.03  NaN
1136  Ahmedabad  2018-02-10  185.77     NaN  124.01  172.84  186.66  NaN
560   Ahmedabad  2016-07-14   38.13     NaN   46.51   48.06   43.98  NaN
1048  Ahmedabad  2017-11-14  207.19     NaN  118.02  146.18  159.36  NaN
1463  Ahmedabad  2019-01-03  131.50     NaN  119.68   75.82   88.04  NaN
1417  Ahmedabad  2018-11-18  127.46     NaN  108.81   77.65  129.43  NaN
1420  Ahmedabad  2018-11-21   86.52     NaN  115.87   66.59   81.77  NaN
1407  Ahmedabad  2018-11-08  205.21     NaN   93.31  100.87   77.22  NaN
1127  Ahmedabad  2018-02-01  189.12     NaN   94.00  178.13  160.97  NaN
1746  Ahmedabad  2019-10-13  194.36  335.86  119.30  207.05  223.66  NaN

          CO     SO2     O3  Benzene  Toluene  Xylene     AQI AQI_Bucket  \
1145  132.47     NaN  44.06     0.74     5.81    3.21  2049.0     Severe
1136  124.01  120.94  40.97     0.74     5.81    3.21  1917.0     Severe
560    46.51   23.13    NaN     0.00     0.00    0.00  1842.0     Severe
1048  118.02  160.06  37.21    63.79     2.22   32.14  1747.0     Severe
1463  119.68   55.29  43.25     4.09    32.42    7.00  1719.0     Severe
1417  108.81   63.63  48.32     3.97    32.20    6.81  1672.0     Severe
1420  115.87   44.24  36.00     3.97    32.20    6.81  1646.0     Severe
1407   93.31   75.95  61.17    20.41    55.29   13.92  1630.0     Severe
1127   94.00  168.44  39.06     0.74     5.81    3.21  1613.0     Severe
1746  119.30     NaN  27.16     1.15    23.37    2.04  1595.0     Severe

     AQI_Category
1145       Severe
1136       Severe
560        Severe
1048       Severe
1463       Severe
1417       Severe
1420       Severe
1407       Severe
1127       Severe
1746       Severe

In [14]:
df.groupby('City')[['PM2.5', 'PM10', 'NO2', 'CO', 'AQI']].mean()

                         PM2.5        PM10        NO2         CO         AQI
City
Ahmedabad            67.872395  112.786826  60.345614  22.191213  452.122939
Aizawl               16.988545   23.286364   0.367027   0.281441   34.765766
Amaravati            38.076711   76.157488  21.720036   0.613811   95.299643
Amritsar             55.102253  115.028629  18.481492   0.559584  119.920959
Bengaluru            35.871628   83.404444  28.308753   1.669216   94.318325
Bhopal               50.207230  119.715755  31.373561   0.880719  132.827338
Brajrajnagar         63.896196  123.516117  17.001319   1.837915  150.280505
Chandigarh           41.311882   85.795819  11.718508   0.630401   96.498328
Chennai              50.154366   62.834404  16.548647   1.018973  114.502654
Coimbatore           29.441458   38.896589  27.652537   0.948280   73.023256
Delhi               117.549770  232.902974  50.763969   1.985213  259.487744
Ernakulam            24.880658   47.945066   3.657129   1.623421   92.359477
Gurugram            115.609192  191.270244  23.867143   1.304701  225.123882
Guwahati             61.487773  113.819253  13.542586   0.734444  140.111111
Hyderabad            47.092885   91.943344  28.504208   0.604127  109.207447
Jaipur               54.686841  123.805193  32.471963   0.807475  133.679159
Jorapokhar           64.348118  152.143935   9.302303   0.715180  159.251621
Kochi                31.540506   66.114430  14.461118   1.294114  104.284810
Kolkata              64.653342  116.082175  40.802745   0.850040  140.566313
Lucknow             109.793585         NaN  33.889513   1.750101  217.973059
Mumbai               35.175855   96.629429  25.461048   1.221256  105.352258
Patna               124.764299  126.747958  39.114583   1.585274  240.782042
Shillong             24.728750   35.840683   2.878550   0.271805   53.795122
Talcher              61.987895  166.550146  13.367288   1.811342  172.886819
Thiruvananthapuram   28.235115   53.222314   9.483270   0.978561   75.878327
Visakhapatnam        47.615159  106.885609  37.194611   0.854335  117.269855